services:

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    networks:
      - salon-network

  customerservice:
    build:
      context: .
      dockerfile: ./CustomerService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  staffservice:
    build:
      context: .
      dockerfile: ./StaffService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  serviceservice:
    build:
      context: .
      dockerfile: ./ServiceService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  appointmentservice:
    build:
      context: .
      dockerfile: ./AppointmentService/Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  paymentservice:
    build:
      context: .
      dockerfile: ./PaymentService/Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  feedbackservice:
    build:
      context: .
      dockerfile: ./FeedbackService/Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  apigateway:
    build:
      context: .
      dockerfile: ./APIGateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=consul
    networks:
      - salon-network

  # webapp:
  #   build:
  #     context: ../Frontend/WebApp
  #     dockerfile: ../../Docker/WebApp/Dockerfile
  #   ports:
  #     - "5007:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   networks:
  #     - salon-network

# Định nghĩa mạng Docker
networks:
  salon-network:
    driver: bridge